print("Tulud")
print("Kirjuta kui palju sa teenid numbrina ja kui ei teeni sisesta 0")
print("Kui palju sa teenid taskurahas ema/isa poolt?")
taskuraha = input()
# jättab meelde taskuraha
print("Kui palju sa teenid vanaema/vanaisa poolt?")
vanaraha = input()
# jättab meelde vanama ja vanaisa raha
print("Kui palju sa teenid töökohalt?")
palk = input()
# jättab meelde palga
print("Kui palju sa teenid toetustest?")
toetused = input()
# jättab meelde toetused
print("Kui palju sa teenid muudest sissetulekutest?")
sissemuu = input()
kokku = int(taskuraha) + int(vanaraha) + int(palk) + int(toetused) + int(sissemuu)
print("sinul on kokku raha: " + str(kokku))
print("Kulud:")
print("Kui palju sa kulutad toidu peale?")
toit = input()
print("Kui palju sa kulutad arvete peale?")
arved = input()
print("Kui palju sa kulutad meelelahutuse peale?")
meelelahutus = input()
print("Kui palju sa kulutad subscriptionite või muu teenuste peale?")
subscriptionid = input()
print("Kui palju sa kulutad transpordi peale?")
transport = input()
print("Kui midagi muu peale oled kulutanud mis ei olnud siin nimekirjas kirjuta siia")
muu = input()
netopalk = int(toit) + int(arved) + int(meelelahutus) + int(subscriptionid) + int(transport) + int(muu)
jääk = kokku - netopalk
print("Sinu jääk on: " + str(jääk))
